//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMuVoter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenMuVoter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openmu.com/WebShop/core.php?p=log.
        /// </summary>
        internal static string GetCredits_URL {
            get {
                return ResourceManager.GetString("GetCredits_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openmu.com/?p=votesys.
        /// </summary>
        internal static string Vote_URL {
            get {
                return ResourceManager.GetString("Vote_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openmu.com/?p=votesys&amp;id=20
        ///http://openmu.com/?p=votesys&amp;id=19
        ///http://openmu.com/?p=votesys&amp;id=18
        ///http://openmu.com/?p=votesys&amp;id=17
        ///http://openmu.com/?p=votesys&amp;id=16
        ///http://openmu.com/?p=votesys&amp;id=15
        ///http://openmu.com/?p=votesys&amp;id=14
        ///http://openmu.com/?p=votesys&amp;id=13
        ///http://openmu.com/?p=votesys&amp;id=11
        ///http://openmu.com/?p=votesys&amp;id=10
        ///http://openmu.com/?p=votesys&amp;id=9
        ///http://openmu.com/?p=votesys&amp;id=8
        ///http://openmu.com/?p=votesys&amp;id=7
        ///http://openmu.com/?p=votesys&amp;id=6
        ///http://openm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VotingSites_URLs {
            get {
                return ResourceManager.GetString("VotingSites_URLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openmu.com/WebShop/.
        /// </summary>
        internal static string WebShop_URL {
            get {
                return ResourceManager.GetString("WebShop_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openmu.com/WebShop/core.php?p=reward.
        /// </summary>
        internal static string WebshopReward_URL {
            get {
                return ResourceManager.GetString("WebshopReward_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openmu.com/WebShop/?op=yes.
        /// </summary>
        internal static string WebshopVote_URL {
            get {
                return ResourceManager.GetString("WebshopVote_URL", resourceCulture);
            }
        }
    }
}
